# Memory
shared_buffers = 2GB
work_mem = 64MB
maintenance_work_mem = 512MB
effective_cache_size = 6GB

# Checkpoints
checkpoint_completion_target = 0.9
wal_buffers = 16MB
max_wal_size = 4GB
min_wal_size = 1GB

# Planner
default_statistics_target = 100
random_page_cost = 1.1
effective_io_concurrency = 200

# Connections
max_connections = 100
listen_addresses = '*'
